config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bookings, only: [:index,:destroy, :show]
  resources :boyfriends do
   resources :bookings, only: [ :new, :create, :edit, :update ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :boyfriend

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/boyfriend.rb
class Boyfriend < ApplicationRecord
  has_many :users
  has_many :bookings

  validates :first_name, :last_name, :age, :category, :email, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :boyfriend
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
   @booking = Booking.find(params[:id])
  end

  def index
    @bookings = Booking.all.order(created_at: :desc)
  end

  def new
    @boyfriend = Boyfriend.find(params[:boyfriend_id])
    @booking = Booking.new
   end

  def create
   @boyfriend = Boyfriend.find(params[:boyfriend_id])
   @booking = Booking.new(booking_params)
   @booking.boyfriend = @boyfriend
   @booking.user = current_user
    if @booking.save
     redirect_to bookings_path
    else
      render :new
    end
  end

  def destroy
   @booking = Booking.find(params[:id])
   @booking.destroy
   redirect_to bookings_path
  end

 private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/boyfriends_controller.rb
class BoyfriendsController < ApplicationController
  def index
    if params[:query].present?
      sql_query = "first_name ILIKE :query OR category ILIKE :query"
      @boyfriends = Boyfriend.where(sql_query, query: "%#{params[:query]}%")
    else
      @boyfriends = Boyfriend.all
    end
  end


  def show
    @boyfriend = Boyfriend.find(params[:id])
  end

  def create
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @reviews = reviews.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # current_user
  # user_signed_in?
end

app/views/bookings/index.html.erb
<div class="container">
 <br> 
 <h1>Congratulation, Your booking has been confirmed!</h1>
</div>
  <div class= " bg-white rounded shadow h-100 card-body align-items-center py-5 form-new">
    <% @bookings.each do |booking| %>
      <h2><em><%= booking.boyfriend.first_name %> <%= booking.boyfriend.last_name %></em>
      <br>
      <br>
      <p>Start Date: <%= booking.start_date %></p>
      <p>End Date: <%= booking.end_date %></p>
     <div class= "btn btn-light">
       <%=link_to "Delete", booking_path(booking), method: :delete %>
     </div>
       <hr>
    <%end%>
    </ol>
  </div>

app/views/bookings/new.html.erb
<div class= "container py-5 mb-40">
  <div class= "d-flex align-items-center justify-content-center mb-4">
   <h2><strong>Book Now</strong><h2>
  </div>
  <div class= "bg-white rounded shadow h-100 card-body align-items-center py-5 form-new">

    <%= simple_form_for ([@boyfriend, @booking]), remote: true do |f| %>
     <%= f.input :start_date, as: :date, html5: true, input_html: {class: 'form-input'} %>
     <%= f.input :end_date, as: :date, html5: true, input_html: {class: 'form-input'} %>

    <%= f.submit "Confirm Booking", class: 'btn btn-gradient' %>
    <% end %>
    <%= link_to 'Cancel Booking', boyfriend_path(@boyfriend), class: 'btn btn-ghost' %>


  </div>
</div>

app/views/bookings/show.html.erb
<h2>Your booking has been confirmed!</h2>

app/views/boyfriends/index.html.erb
<div class="search box">
  
   <%= form_tag boyfriends_path, method: :get do %>
   <div class="search-boyfriend mb-4 d-flex" >
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a boyfriend..."
    %>
      
      <%= submit_tag "Search", class: "btn btn-primary" %>
      </div>
  <% end %>
  
   

  </div>
</div>

<div class="cover mb-4 d-flex align-items-center justify-content-center" >
  <h1>BOYFRIEND LIST</h1>
</div>
<div class="cover mb-4 d-flex align-items-center justify-content-center" >
<div class= "row ">
<div class ="col">
  <% @boyfriends.each do |boyfriend| %>
    <div class="card-product">
      <img src= "<%= boyfriend.photo %>" />
      <div class="card-product-infos">
        <%= link_to boyfriend_path(boyfriend) do %>
          <h2><%= boyfriend.first_name%>
          <%= boyfriend.last_name %></h2>
          <p><%= boyfriend.boyfriend_description %></p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
</div>
</div>

app/views/boyfriends/show.html.erb
    <div>
      <div class="container">
         <div cover mb-4 d-flex align-items-center justify-content-center>
           <h1>My Profile</h1>

         </div>
          <div class="d-flex row justify-content-center">
            <div class="col-lg-4">
               <div class="card bg-light my-3">
                    <div class="card-body d-flex align-items-center">
                      <h2 class="card-title fw-bolder"> <%= @boyfriend.first_name %> <%= @boyfriend.last_name %> </h2>
                        </div>
                          <ul class="list-group list-group-flush">
                           <li class="list-group-item">Description: <em>"<%= @boyfriend.boyfriend_description%>"</em></li>
                           <li class="list-group-item"> Category: <%= @boyfriend.category %>
                           <li class="list-group-item">Age: <%= @boyfriend.age %></li>
                           <li class="list-group-item"> Email: <%=@boyfriend.email %></li>
                           <li class="list-group-item"> Contact Number: <%= @boyfriend.phone_number %></li>
                           <li class="list-group-item"> Address: <%= @boyfriend.address %></li>
                           <li class="list-group-item"> Price: <%= @boyfriend.price %></li>
                          </ul>
                           <%= link_to "Book!", new_boyfriend_booking_path(@boyfriend), class: 'text-center', class: 'btn btn-gradient m-4'%>
                </div>
            </div>
          </div>

        <%= link_to 'Back',:back, class: 'btn btn-gradient' %>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RENT A Boyfriend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
<!-- HERO -->
    <div class="hero vh-100 d-flex align-items-center" id="home">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 mx-auto text-center">
                    <h1 class="display-4 text-white">Rent a boyfriend</h1>
                    <p class="text-white my-3">Rent A Boyfriend is a dating service that matches women with vetted, professional men for friendship or even events.</p>
                    <a href="#" class="btn me-2 btn-primary">Get Started</a>
                    <%= link_to "Book now!", boyfriends_path, class: "btn btn-outline-light" %>
                </div>
            </div>
        </div>
    </div>
<!-- SERVICES -->
    <section id="services">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md-8 mx-auto text-center">
                    <h1>How to proceed</h1>
                    <p></p>
                </div>
            </div>
            <div class="row g-4">
                <div class="col-lg-4 col-sm-6">
                    <div class="service card-effect bounceInUp">
                        <h5 class="mt-4 mb-2">1.</h5>
                        <p>Sign up or Log in on our platform</p>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <div class="service card-effect">
                        <h5 class="mt-4 mb-2">2.</h5>
                        <p>Make your selection</p>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <div class="service card-effect">
                        <h5 class="mt-4 mb-2">3.</h5>
                        <p>Confirm your booking</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
<!-- FEATURES -->
    <section class="row w-100 py-10 bg-light" id="features">
            <div class="container">
              <div class="row text-center">
                <div class="col-md text-justify">
                      <h6 class="text-primary">HIRE A BOYFRIEND</h6>
                        <h1>Just like hiring a plumber or an electrician</h1>
                        <p>Ever since the advent of social media and selfie stick, people have become more and more conscious about their looks, specially women.
                        <br>
                        But what if you do not find a man who is good looking enough to be your boyfriend?
                        <br>
                        <b>Here comes the solution!</b>
                        <br>
                        Rent A Boyfriend is a platform where you can hire boyfriends for a particular task.
                        <br>
                        All you need to do is pay online and make your choice from the list.</p>
                </div>
                <div class="col-md ml-5"><%= image_tag "features.jpg", style: 'height:600px;width:400px;' %></div>
              </div>
            </div>
    </section>
    <!-- CONTACT -->
    <section id="contact">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md-8 mx-auto text-center">
                    <h6 class="text-primary">CONTACT</h6>
                    <h1>Get In Touch</h1>
                    <p>If you need a boyfriend for an occasion, simply visit our website and rent one. We provide all of our customers with handsome men who are willing to go out with you as your pretend boyfriend. Whether it is a party or a wedding reception, we can help you look like you have a boyfriend by your side.</p>
                </div>
            </div>
            <form action="" class="row g-3 justify-content-center">
                <div class="col-md-5">
                    <input type="text" class="form-control" placeholder="Full Name">
                </div>
                <div class="col-md-5">
                    <input type="text" class="form-control" placeholder="Enter E-mail">
                </div>
                <div class="col-md-10">
                    <input type="text" class="form-control" placeholder="Enter Subject">
                </div>
                <div class="col-md-10">
                    <textarea name="" id="" cols="30" rows="5" class="form-control"
                        placeholder="Enter Message"></textarea>
                </div>
                <div class="col-md-10 d-grid">
                    <button class="btn btn-primary">Contact</button>
                </div>
            </form>

        </div>
    </section>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Made with <i class="fas fa-heart"></i> by OneCliQ™
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/JordanJogool/rent-a-boyfriend/main/logov2.png" %>
  <% end %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <%= link_to "Home", root_path, class: "nav-link" %>
    </li>
      <li class="nav-item">
    <%= link_to "Book a boyfriend", boyfriends_path, class: "nav-link" %>
    </li>
      <% if current_user %>
      <li class="nav-item dropdown">
        <div class= "dropdown-toggle navbar-email", id= "navbarDropdown", data-toggle="dropdown",
        ><%= current_user.email %></div>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to edit_user_registration_path, class: "dropdown-item #{'active fw-bold' if current_page?(edit_user_registration_path)}" do %>
            <div class="fa fa-cog"></div>
            <b>Account settings</b>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
            <div class="fa fa-sign-out-alt"></div>
            <b>Sign out</b>
          <% end %>
        </div>
      </li>

    <% else %>
        <%= link_to "Log in", new_user_session_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_session_path)}" %>
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_registration_path)}" %>
      <% end %>
    </ul>
  </div>
</div>